SELECT * FROM SA.USERS;
SELECT * FROM SA.TRAIN;
SELECT * FROM SYS.SYSTABLES WHERE TABLETYPE = 'T';

DROP TABLE SA.Booking;
DROP TABLE SA.Cancellation_Request;
DROP TABLE SA.Passenger;
DROP TABLE SA.Train;
